name: TLS Integration Tests MicroK8s

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tls-integration-test-microk8s:
    name: TLS Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run tls integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: sg microk8s -c "tox -e tls-integration -- --model testing"
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: mongodb-k8s
          model: testing